// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-studies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function getPublicSupabase() {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) {
    throw new Error("Supabase env not configured (SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY)");
  }
  return createClient(url, anon, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-studies.ts
var list_studies_default = defineTool({
  name: "list_studies",
  title: "Listar estudos",
  description: "Lista os estudos de frete cadastrados (id, nome, transportadora, status, data de cria\xE7\xE3o).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de estudos a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = getPublicSupabase();
    const { data, error } = await supabase.from("studies").select("id, name, carrier_name, status, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { studies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-study-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_study_summary_default = defineTool2({
  name: "get_study_summary",
  title: "Resumo do estudo",
  description: "Retorna o resumo de um estudo: total de notas, pago, proposto, economia (pago - proposto), % de economia e prazos m\xE9dios (real vs proposto).",
  inputSchema: {
    study_id: z2.string().uuid().describe("UUID do estudo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ study_id }) => {
    const supabase = getPublicSupabase();
    const [{ data: study, error: sErr }, { data: summaries, error: rErr }] = await Promise.all([
      supabase.from("studies").select("id, name, carrier_name, status, created_at").eq("id", study_id).maybeSingle(),
      supabase.rpc("study_summaries")
    ]);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    if (!study) return { content: [{ type: "text", text: "Estudo n\xE3o encontrado." }], isError: true };
    if (rErr) return { content: [{ type: "text", text: rErr.message }], isError: true };
    const summary = (summaries ?? []).find((s) => s.study_id === study_id) ?? null;
    const payload = { study, summary };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/analyze-by-uf.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var analyze_by_uf_default = defineTool3({
  name: "analyze_by_uf",
  title: "An\xE1lise por UF",
  description: "Agrupa os resultados da simula\xE7\xE3o de um estudo por UF: total pago, total proposto, diferen\xE7a (pago - proposto) e % de diferen\xE7a. Positivo = economia proposta / negativo = proposta mais cara.",
  inputSchema: {
    study_id: z3.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ study_id }) => {
    const supabase = getPublicSupabase();
    const pageSize = 1e3;
    let all = [];
    for (let from = 0; ; from += pageSize) {
      const { data, error } = await supabase.from("simulations").select("uf:shipment_row_id, valor_cobrado, frete_final, match_status").eq("study_id", study_id).order("id").range(from, from + pageSize - 1);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      if (!data || data.length === 0) break;
      all = all.concat(data);
      if (data.length < pageSize) break;
    }
    const shipmentIds = Array.from(new Set(all.map((r) => r.uf))).filter(Boolean);
    const ufMap = /* @__PURE__ */ new Map();
    for (let i = 0; i < shipmentIds.length; i += 200) {
      const slice = shipmentIds.slice(i, i + 200);
      const { data, error } = await supabase.from("shipments_paid").select("id, uf").in("id", slice);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      (data ?? []).forEach((r) => ufMap.set(r.id, r.uf));
    }
    const byUf = /* @__PURE__ */ new Map();
    for (const r of all) {
      if (r.match_status === "NOT_FOUND") continue;
      const uf = ufMap.get(r.uf) ?? "??";
      const cur = byUf.get(uf) ?? { pago: 0, proposto: 0, n: 0 };
      cur.pago += Number(r.valor_cobrado ?? 0);
      cur.proposto += Number(r.frete_final ?? 0);
      cur.n += 1;
      byUf.set(uf, cur);
    }
    const rows = [...byUf.entries()].map(([uf, v]) => {
      const dif = v.pago - v.proposto;
      const pct = v.proposto ? dif / v.proposto * 100 : 0;
      return {
        uf,
        notas: v.n,
        total_pago: Math.round(v.pago * 100) / 100,
        total_proposto: Math.round(v.proposto * 100) / 100,
        diferenca: Math.round(dif * 100) / 100,
        pct_diferenca: Math.round(pct * 10) / 10
      };
    }).sort((a, b) => b.diferenca - a.diferenca);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { by_uf: rows }
    };
  }
});

// src/lib/mcp/tools/top-cities-to-adjust.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
var top_cities_to_adjust_default = defineTool4({
  name: "top_cities_to_adjust",
  title: "Cidades para ajustar",
  description: "Retorna as cidades onde a proposta da transportadora est\xE1 mais cara que o valor pago hoje (candidatas a ajuste na negocia\xE7\xE3o), ordenadas pela maior perda absoluta.",
  inputSchema: {
    study_id: z4.string().uuid(),
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ study_id, limit }) => {
    const supabase = getPublicSupabase();
    const pageSize = 1e3;
    let sims = [];
    for (let from = 0; ; from += pageSize) {
      const { data, error } = await supabase.from("simulations").select("shipment_row_id, valor_cobrado, frete_final, match_status").eq("study_id", study_id).order("id").range(from, from + pageSize - 1);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      if (!data || data.length === 0) break;
      sims = sims.concat(data);
      if (data.length < pageSize) break;
    }
    const ids = Array.from(new Set(sims.map((s) => s.shipment_row_id)));
    const meta = /* @__PURE__ */ new Map();
    for (let i = 0; i < ids.length; i += 200) {
      const slice = ids.slice(i, i + 200);
      const { data, error } = await supabase.from("shipments_paid").select("id, uf, cidade_corrigida").in("id", slice);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      (data ?? []).forEach(
        (r) => meta.set(r.id, { uf: r.uf, cidade: r.cidade_corrigida })
      );
    }
    const agg = /* @__PURE__ */ new Map();
    for (const s of sims) {
      if (s.match_status === "NOT_FOUND") continue;
      const m = meta.get(s.shipment_row_id);
      if (!m) continue;
      const key = `${m.uf}|${m.cidade}`;
      const cur = agg.get(key) ?? { uf: m.uf, cidade: m.cidade, pago: 0, proposto: 0, n: 0 };
      cur.pago += Number(s.valor_cobrado ?? 0);
      cur.proposto += Number(s.frete_final ?? 0);
      cur.n += 1;
      agg.set(key, cur);
    }
    const rows = [...agg.values()].map((v) => {
      const dif = v.pago - v.proposto;
      const pct = v.proposto ? dif / v.proposto * 100 : 0;
      return {
        uf: v.uf,
        cidade: v.cidade,
        notas: v.n,
        total_pago: Math.round(v.pago * 100) / 100,
        total_proposto: Math.round(v.proposto * 100) / 100,
        perda: Math.round(-dif * 100) / 100,
        // quanto a proposta está mais cara
        pct_dif: Math.round(pct * 10) / 10
      };
    }).filter((r) => r.perda > 0).sort((a, b) => b.perda - a.perda).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { cities: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "frete-analise-mcp",
  title: "An\xE1lise de Fretes MCP",
  version: "0.1.0",
  instructions: "Ferramentas de leitura para explorar estudos de simula\xE7\xE3o de fretes: listar estudos, obter resumo de um estudo, agrupar resultados por UF e listar cidades onde a proposta da transportadora est\xE1 mais cara que o valor pago hoje.",
  tools: [list_studies_default, get_study_summary_default, analyze_by_uf_default, top_cities_to_adjust_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
